# See full Decap documentation for further configuration: https://decapcms.org/docs/intro/
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
publish_mode: editorial_workflow
media_folder: src/assets/images/blog # Location where files will be stored in the repo - we store them in src so that Astro can optimize them.
public_folder: src/assets/images/blog  # Ensure that this path is the same as the media_folder path above.
site_url: https://hacbed.org # Displays a link to home page in the top-right corner of the CMS dashboard
logo_url: https://codestitch.app/frontend/images/logo.png # change url to a link to the image you want to use, no file paths, must be a URL
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
    label: "Blog" # Used in the admin dashboard UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["draft", "published"],
          default: "draft"
        }

  - name: "team"
    label: "Team Members"
    folder: "src/content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Job Title", name: "jobTitle", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", media_folder: "/src/assets/images" }
      - { label: "Display Order", name: "order", widget: "number", required: false, value_type: "int" }

  - name: "board"
    label: "Board Members"
    folder: "src/content/board"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Job Title", name: "jobTitle", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", media_folder: "/src/assets/images" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Display Order", name: "order", widget: "number", required: false, value_type: "int" }

  - name: "founders"
    label: "Founders"
    folder: "src/content/founders"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Image", name: "image", widget: "image", media_folder: "/src/assets/images" }
      - { label: "Video", name: "video", widget: "file", required: false, media_folder: "/public/assets/videos", public_folder: "/assets/videos", hint: "Upload a video file (MP4 recommended)" }
      - { label: "Video Caption", name: "videoCaption", widget: "string", required: false, hint: "Caption that displays with the video" }
      - { label: "Display Order", name: "order", widget: "number", required: false }

  - name: "about"
    label: "About"
    folder: "src/content/about"
    create: false
    slug: "about"
    fields:
      - { label: "Page ID", name: "pageId", widget: "string", hint: "Unique identifier for the page (e.g., 'about', 'services')" }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["draft", "published"],
          default: "draft"
        }
      # About page fields
      - { label: "Main Content", name: "mainContent", widget: "markdown" }
      - { label: "Mission Title", name: "missionTitle", widget: "string", required: false }
      - { label: "Mission Statement", name: "missionStatement", widget: "string", required: false }
      - { label: "Mission Content", name: "missionContent", widget: "markdown", required: false }
    

  - name: "projects" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
    label: "Projects" # Used in the admin dashboard UI
    folder: "src/content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { 
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["Capacity Building & Technical Assistance", "Network Coordination","Strategic & Community-Based Planning", "Past Support"] 
        }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }